# roles/dnsmasq/tasks/main.yml
---
- name: Install Dnsmasq
  yum:
    pkg: dnsmasq
    state: present
  tags: dnsmasq

- name: Set configuration file
  template:
    src: etc_dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    validate: 'dnsmasq --test --conf-file=%s'
  notify: restart dnsmasq
  tags: dnsmasq

- name: Make sure Dnsmasq is running
  service:
    name: dnsmasq
    state: started
    enabled: yes
  tags: dnsmasq

- name: Check if firewalld is running
  command: firewall-cmd --state
  ignore_errors: yes
  changed_when: false
  register: firewalld_running
  tags: dnsmasq

- name: Apply DNS firewall rules
  firewalld:
    service: dns
    permanent: true
    state: enabled
    zone: public
  when: firewalld_running|success
  with_items:
    - 'dns'
  notify:
    restart firewalld
  tags: dnsmasq

- name: Apply DHCP firewall rules
  firewalld:
    service: dhcp
    permanent: true
    state: enabled
    zone: public
  when: firewalld_running|success
  with_items:
    - 'dhcp'
  when: dnsmasq_dhcp_ranges is defined
  notify:
    restart firewalld
  tags: dnsmasq
